version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 1157:1157
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin123
            
    db:
        image: mysql/mysql-server:latest
        container_name: my-mysql
        restart: always
        environment:
          - MYSQL_DATABASE=root
          - MYSQL_ROOT_PASSWORD=
        ports:
          - '11000:11000'
        volumes:
          - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local

